name: Build

on: [push]

jobs:
  test_Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev libsdl2-image-dev
        
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B .
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}/src

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: |
        cmake --build . --config Release

    - uses: actions/upload-artifact@v4
      with:
        name: princess_linux
        path: /home/runner/work/princess-of-petals/princess-of-petals/

  test_Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v1

    - name: install packages
      shell: pwsh
      run: |
        choco install nasm
        echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: libsdl-org/setup-sdl@main
      id: sdl
      with:
        install-linux-dependencies: true
        version: 2-latest
        version-sdl-image: 2-latest
        add-to-environment: true

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Info
      shell: bash
      run: |
        ls $SDL2_image_ROOT/bin
        echo
        ls $SDL2_image_ROOT/include
        echo
        ls $SDL2_image_ROOT/lib
        echo
        ls $SDL2_image_ROOT/share

    - name: Build
      shell: cmd
      run: |
        cp %SDL2_image_ROOT%\include\SDL2\SDL_image.h %SDL2_ROOT%\include\SDL2
        cp -a %SDL2_image_ROOT%\lib\. %SDL2_ROOT%\lib
        src\build.bat release %SDL2_ROOT% %SDL2_image_ROOT%

    - name: Copy Dlls
      shell: cmd
      run: |
        cp %SDL2_ROOT%\bin\SDL2.dll ${{ github.workspace }}
        cp %SDL2_image_ROOT%\bin\SDL2_imaged.dll ${{ github.workspace }}

    - uses: actions/upload-artifact@v4
      with:
        name: princess_windows
        path: ${{ github.workspace }}
